import type { SocialMessage, SocialRoom, SocialUser } from './types'

export const socialPreviewUsers: SocialUser[] = [
  {
    id: 'irem-aydin',
    displayName: 'İrem Aydın',
    handle: '@iremAYDN',
    initials: 'İA',
    avatarTone: 0,
    presence: 'online',
    currentTrack: {
      id: 'social:sonsuz',
      videoId: 'social-sonsuz',
      title: 'Sonsuz',
      artist: 'Pusula',
      duration: 261,
      position: 84,
      cover: 4,
      isPlaying: true,
    },
    reactionCount: 3,
    lastReaction: '♥',
  },
  {
    id: 'mert-koc',
    displayName: 'Mert Koç',
    handle: '@mertkoc',
    initials: 'MK',
    avatarTone: 1,
    presence: 'online',
    currentTrack: {
      id: 'social:geceye-donus',
      videoId: 'social-geceye-donus',
      title: 'Geceye Dönüş',
      artist: 'Mavi Atlas',
      duration: 236,
      position: 130,
      cover: 0,
      isPlaying: true,
    },
    reactionCount: 2,
    lastReaction: '🔥',
  },
  {
    id: 'zeynep-kaya',
    displayName: 'Zeynep Kaya',
    handle: '@zeynepkaya',
    initials: 'ZK',
    avatarTone: 2,
    presence: 'online',
    currentTrack: {
      id: 'social:yalniz-degilsin',
      videoId: 'social-yalniz-degilsin',
      title: 'Yalnız Değilsin',
      artist: 'Ritim Editörleri',
      duration: 228,
      position: 58,
      cover: 3,
      isPlaying: true,
    },
    reactionCount: 1,
    lastReaction: '✨',
  },
  {
    id: 'can-ozkan',
    displayName: 'Can Özkan',
    handle: '@canozkan',
    initials: 'CÖ',
    avatarTone: 3,
    presence: 'online',
    currentTrack: {
      id: 'social:lofi-zamani',
      videoId: 'social-lofi-zamani',
      title: 'Lo-Fi Zamanı',
      artist: 'Ritim Editörleri',
      duration: 217,
      position: 62,
      cover: 2,
      isPlaying: true,
    },
    reactionCount: 2,
    lastReaction: '💯',
  },
  {
    id: 'duru-sahin',
    displayName: 'Duru Şahin',
    handle: '@durushn',
    initials: 'DŞ',
    avatarTone: 4,
    presence: 'online',
    currentTrack: {
      id: 'social:sehir-isiklari',
      videoId: 'social-sehir-isiklari',
      title: 'Şehir Işıkları',
      artist: 'Ritim Editörleri',
      duration: 251,
      position: 153,
      cover: 1,
      isPlaying: true,
    },
    reactionCount: 1,
    lastReaction: '♥',
  },
]

export const socialPreviewRooms: SocialRoom[] = [
  { id: 'room-gece', title: 'Geceye Dönüş', memberCount: 8, cover: 0, isLive: true, memberInitials: ['İA', 'MK', 'ZK', 'CÖ'] },
  { id: 'room-sehir', title: 'Şehir Işıkları', memberCount: 5, cover: 1, isLive: true, memberInitials: ['DŞ', 'MK', 'İA'] },
  { id: 'room-lofi', title: 'Lo-Fi Zamanı', memberCount: 6, cover: 2, isLive: true, memberInitials: ['CÖ', 'ZK'] },
  { id: 'room-kesif', title: 'Yeni Keşifler', memberCount: 3, cover: 4, isLive: true, memberInitials: ['İA', 'DŞ'] },
]

export const socialPreviewMessages: Record<string, SocialMessage[]> = {
  'irem-aydin': [
    { id: 'message-1', senderId: 'irem-aydin', text: 'Selam! Bu parçayı yeni keşfettim.', sentAt: Date.now() - 1000 * 60 * 6 },
    { id: 'message-2', senderId: 'current-user', text: 'Harika seçim, birlikte dinleyelim mi?', sentAt: Date.now() - 1000 * 60 * 4 },
    { id: 'message-3', senderId: 'irem-aydin', text: 'Olur, odaya katılıyorum 🎧', sentAt: Date.now() - 1000 * 60 * 2 },
  ],
}
